name: Swift Package Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.0'
      - name: Debug Setup Swift
        run: |
          echo "Swift setup failed. Capturing logs..."
          ls -la /usr/bin
          cat /etc/os-release
      - name: Build and test
        run: swift test --enable-test-discovery
